services:



  web:
    build:
      context: .
      target: development
    init: true
    ports:
      - 80
    restart: always
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
